### ISSUE TITLE
请同步aria2ng更新

### ISSUE THREAD

**Issue by Aurora-Simba** [15dd/Aria2_Launcher#1]
ariang已更新1.3.6：https://github.com/mayswind/AriaNg/releases/latest
请同步更新

**Comment by 15dd** [comment]
这个项目停止维护和更新了，可能之后会用C#写一个新的

**Comment by Aurora-Simba** [comment]
十分期待，无法忍受其它一些GUI基于electron的大占用

**Comment by 15dd** [comment]
我也受不了所以才写了这个软件，不过最近在忙安卓项目，暂时没空搞这个（暑假期间都不会搞）。还有就是继续用c++和qt写这个软件，不用c#。

**Comment by Aurora-Simba** [comment]
> 我也受不了所以才写了这个软件，不过最近在忙安卓项目，暂时没空搞这个（暑假期间都不会搞）。还有就是继续用c++和qt写这个软件，不用c#。

时隔两年半，aria2又有了新的发行版，想问问您的安排

**Comment by 15dd** [comment]
> > 我也受不了所以才写了这个软件，不过最近在忙安卓项目，暂时没空搞这个（暑假期间都不会搞）。还有就是继续用c++和qt写这个软件，不用c#。
> 
> 时隔两年半，aria2又有了新的发行版，想问问您的安排

跟aria2相关的不搞了，停止更新
